### ISSUE TITLE
ImportError during Docker image build

### ISSUE THREAD

**Issue by mowtee** [mattieserver/netbox-topology-views#336]
### NetBox version

v3.5.3

### Topology Views version

v3.5.0

### Steps to Reproduce

1. Start with running Netbox Docker v3.5.3 installation
2. docker compose down
3. Create plugin_requirements.txt:
`netbox-topology-views`
4. Add netbox_topology_views to configuration/configuration.py
5. Create Dockerfile-Plugins:
```
FROM netboxcommunity/netbox:latest

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
RUN mkdir -p /opt/netbox/netbox/static/netbox_topology_views/img
COPY configuration/configuration.py /etc/netbox/config/configuration.py
RUN SECRET_KEY="<key>" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate netbox_topology_views
RUN SECRET_KEY="<key>" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
```
6. Modify docker-compose.override.yml:
```
version: '3.4'
services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    ports:
    - 8080:8080
    environment:
      <some ldap related settings>
  netbox-worker:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  netbox-housekeeping:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
  tls:
    image: caddy:2-alpine
    depends_on:
      - netbox
    volumes:
      - ./cert/cert.crt:/etc/ssl/private/cert.crt:ro,z
      - ./cert/key.key:/etc/ssl/private/key.key:ro,z
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80
      - 443:443

```
7. docker compose build --no-cache
8. Error:
```
 > [netbox:latest-plugins 6/7] RUN SECRET_KEY="<key>" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate netbox_topology_views:
#0 1.648 🧬 loaded config '/etc/netbox/config/configuration.py'
#0 1.648 🧬 loaded config '/etc/netbox/config/extra.py'
#0 1.648 🧬 loaded config '/etc/netbox/config/logging.py'
#0 1.648 🧬 loaded config '/etc/netbox/config/plugins.py'
#0 1.648 Traceback (most recent call last):
#0 1.648   File "/opt/netbox/netbox/manage.py", line 10, in <module>
#0 1.648     execute_from_command_line(sys.argv)
#0 1.648   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
#0 1.650     utility.execute()
#0 1.650   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
#0 1.650     django.setup()
#0 1.650   File "/opt/netbox/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
#0 1.652     apps.populate(settings.INSTALLED_APPS)
#0 1.652   File "/opt/netbox/venv/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
#0 1.653     app_config.ready()
#0 1.654   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_topology_views/__init__.py", line 22, in ready
#0 1.654     super().ready()
#0 1.654   File "/opt/netbox/netbox/extras/plugins/__init__.py", line 73, in ready
#0 1.655     menu_items = import_object(f"{self.__module__}.{self.menu_items}")
#0 1.655   File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
#0 1.656     spec.loader.exec_module(module)
#0 1.656   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
#0 1.656   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#0 1.656   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_topology_views/navigation.py", line 1, in <module>
#0 1.656     from extras.plugins import PluginMenu, PluginMenuItem
#0 1.657 ImportError: cannot import name 'PluginMenu' from 'extras.plugins' (/opt/netbox/netbox/extras/plugins/__init__.py)
------
failed to solve: executor failed running [/bin/sh -c SECRET_KEY="<key>" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate netbox_topology_views]: exit code: 1
```

### Expected Behavior

Successful import

Not a Python expert, but shouldn't netbox-topology-views import from extras.plugins.navigation ?

### Observed Behavior

ImportError: cannot import name 'PluginMenu' from 'extras.plugins' (/opt/netbox/netbox/extras/plugins/__init__.py)
